-- Supabase Schema for ASYMOG Portal

-- 1. Key-Value Store (For robust JSON fallback storage caching)
CREATE TABLE IF NOT EXISTS kv_store (
  key TEXT PRIMARY KEY,
  value JSONB NOT NULL
);

-- 2. Settings Table (Global app configuration)
CREATE TABLE IF NOT EXISTS settings (
  id INTEGER PRIMARY KEY,
  "monthlyDuesAmount" NUMERIC,
  "certificatePrice" NUMERIC,
  "licensePrice" NUMERIC,
  "executiveDuesAmount" NUMERIC,
  "cooperativeHandPrice" NUMERIC,
  "cooperativeGraceDay" INTEGER,
  "cooperativeFineAmount" NUMERIC,
  "flutterwaveKey" TEXT,
  "flutterwaveSecretKey" TEXT,
  "cloudinaryUrl" TEXT,
  events JSONB,
  "regularMeetings" JSONB,
  testimonials JSONB,
  "heroImage" TEXT,
  "logoImage" TEXT,
  "presidentImage" TEXT,
  "presidentName" TEXT
);

-- 3. Users Table (Registered Ministers & Executives)
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fullName" TEXT,
  email TEXT UNIQUE NOT NULL,
  phone TEXT,
  "churchName" TEXT,
  "churchAddress" TEXT,
  password TEXT,
  status TEXT DEFAULT 'pending',
  "registrationNumber" TEXT,
  role TEXT,
  "accessKey" TEXT,
  "userType" TEXT DEFAULT 'member',
  "certForm" JSONB,
  "licForm" JSONB,
  "duesPayments" JSONB DEFAULT '[]'::jsonb,
  "certificatePayment" JSONB,
  "licensePayment" JSONB,
  "cooperativePayments" JSONB DEFAULT '[]'::jsonb,
  "cooperativeHands" INTEGER DEFAULT 1,
  "cooperativeEnrollment" BOOLEAN DEFAULT false,
  "profilePicture" TEXT,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 4. Executives Table (Dedicated Executives List)
CREATE TABLE IF NOT EXISTS executives (
  id BIGINT PRIMARY KEY,
  name TEXT,
  role TEXT,
  email TEXT,
  phone TEXT,
  image TEXT,
  "accessKey" TEXT,
  "createdAt" TEXT
);

-- 5. Messages Table (Support Messaging System)
CREATE TABLE IF NOT EXISTS messages (
  id BIGINT PRIMARY KEY,
  "userEmail" TEXT,
  "userName" TEXT,
  subject TEXT,
  message TEXT,
  replies JSONB DEFAULT '[]'::jsonb,
  status TEXT DEFAULT 'unread',
  "createdAt" TEXT
);

-- Enable Realtime for standard tables
alter publication supabase_realtime add table settings;
alter publication supabase_realtime add table users;
alter publication supabase_realtime add table messages;
